version: '3'

services:
  postgres:
    restart: unless-stopped
    container_name: 'skeetry-postgres'
    image: 'postgres:11'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skeetry

  api:
    container_name: 'skeetry-api'
    image: node:lts
    command: yarn start:debug
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/srv/api:rw
    working_dir: /srv/api
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PRISMA_STUDIO_PORT}:5555

volumes:
  pgdata: {}
  redisdata: {}
