version: '3'

services:
  postgres:
    restart: unless-stopped
    container_name: 'skeetry-postgres'
    image: 'postgres:11'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skeetry

  redis:
    container_name: 'skeetry-redis'
    image: 'redis'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

  # TODO: Fix bcrypt error (only in Docker)
  # api:
  #   container_name: 'skeetry-api'
  #   image: node:lts
  #   command: yarn start
  #   ports:
  #     - '127.0.0.1:3000:3000'
  #   volumes:
  #     - .:/srv/api:rw
  #     - /srv/backend/node_modules/bcrypt/
  #   working_dir: /srv/api
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - postgres

volumes:
  pgdata: {}
  redisdata: {}
