name: API

on: [push]

defaults:
  run:
    working-directory: ./packages/backend

jobs:
  build_monorepo:
    name: Build api app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./packages/backend/node_modules
          key: modules-${{ hashFiles('yarn.lock') }}-${{ secrets.CACHE_VERSION }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./packages/backend
        run: yarn --frozen-lockfile

      - name: Build apps
        working-directory: ./packages/backend
        run: yarn build

      # Docker

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: packages/backend/Dockerfile
          context: ./packages/backend
          push: true
          tags: ghcr.io/${{ github.repository }}/skeetry-api:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/skeetry-api:latest
          cache-to: type=inline
